HW15 is completed
gregobal/otus-go pull request #17
Opened 2020-07-05 16:52 UTC by 810411

## Домашнее задание №15 «Докеризация и интеграционное тестирование Календаря»

### Критерии оценки
- [ ] Проект полностью запускается и останавливается с помощью `make up` / `make down` - 3 балла
- [ ] Интеграционные тесты запускаются с помощью `make bdd`. Команда возвращает верный код ответа - 1 балл

Интеграционные тесты покрывают бизнес сценарии:
- [ ] добавление события и обработка бизнес ошибок - 2 балла
- [ ] получение листинга событий на день/неделю/месяц - 2 балла
- [ ] отправка уведомлений - 2 балла

#### Зачёт от 7 баллов

2020-07-05 17:00 UTC, 810411 commented
14 scenarios (14 passed)
38 steps (38 passed)
21.720749ms
testing: warning: no tests to run
PASS
ok      github.com/810411/otus-go/hw12_13_14_15_calendar/tests/integration      13.038s

2020-07-09 06:21 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/23096/6043/

Здравствуйте!
Спасибо за аккуратную работу.

Предварительно
5 / 10


```
--- Failed steps:

  Scenario: successfully adding event # features/add_event.feature:7
    Then the response code should be 200 # features/add_event.feature:17
      Error: expected response code to be: 200, but actual is: 400

  Scenario: add event with same datetime but other user id # features/add_event.feature:54
    Then the response code should be 200 # features/add_event.feature:64
      Error: expected response code to be: 200, but actual is: 400

  Scenario: add event with new datetime # features/add_event.feature:80
    Then the response code should be 200 # features/add_event.feature:90
      Error: expected response code to be: 200, but actual is: 400


14 scenarios (11 passed, 3 failed)
38 steps (32 passed, 3 failed, 3 skipped)
36.4359ms
```

2020-07-09 06:21 UTC, Antonboom commented on .golangci.yml
> +    - gofumpt
а что он требует из неприятного?

2020-07-09 06:21 UTC, Antonboom commented on hw12_13_14_15_calendar/configs/calendar.json
> +    "dsn": "host=postgres port=5432 user=otus password=otus dbname=calendar sslmode=disable"
сесурити :(

2020-07-09 06:21 UTC, Antonboom commented on hw12_13_14_15_calendar/deployments/calendar/Dockerfile
> +COPY . .
следует сначала скопировать go.mod & go.sum, а затем уже весь проект.
иначе слой go mod download не закэшируется толком.

2020-07-09 06:21 UTC, Antonboom commented on hw12_13_14_15_calendar/deployments/goose/Dockerfile
> +COPY --from=builder /go/bin/goose /app/goose
у гуся нет своего готового docker образа?

2020-07-09 06:21 UTC, Antonboom commented on hw12_13_14_15_calendar/deployments/docker-compose.test.yml
> +  calendar:
можно не заводить, они и так в одну сеть по умолчанию объединены

2020-07-09 06:21 UTC, Antonboom commented on hw12_13_14_15_calendar/tests/integration/features/list_events.feature
> +    When I send "GET" request to "http://localhost:8888/events/day?datetime=2020-07-01T00:00:00%2B0000"
здесь разве не `http://calendar:8888` должно быть?

2020-07-09 09:26 UTC, 810411 commented on hw12_13_14_15_calendar/deployments/goose/Dockerfile
> +COPY --from=builder /go/bin/goose /app/goose
что-то глядя на хабе аж глаза разбежались от китайских поделок

2020-07-09 09:29 UTC, 810411 commented on hw12_13_14_15_calendar/tests/integration/features/list_events.feature
> +    When I send "GET" request to "http://localhost:8888/events/day?datetime=2020-07-01T00:00:00%2B0000"
подумалось что описание не должно знать про конкретику окружения, но какой бред только в голову не приходит порой - все равно тесты происходят в конкретном окружении

2020-07-09 09:33 UTC, 810411 commented on .golangci.yml
> +    - gofumpt
а он вылез прям вот на моменте сдачи, у меня версия этого зоопарка еще 27 а в травис уже 28 затянул, в которой он и появился. в общем обломало обновить golangci, не терпелось сдать на проверку

2020-07-09 09:59 UTC, 810411 commented on .golangci.yml
> +    - gofumpt
Добавил gofumpt. Если честно, не очень понял профита с этого. В доках написано -  "This tool is a place to experiment.". Можно если они по экспериментируют без моего участия в этот раз?

2020-07-09 10:31 UTC, Antonboom commented on .golangci.yml
> +    - gofumpt
да, я и не просил его добавлять. мне было интересно ваше мнение :)

2020-07-09 10:32 UTC, Antonboom commented on hw12_13_14_15_calendar/tests/integration/features/list_events.feature
> +    When I send "GET" request to "http://localhost:8888/events/day?datetime=2020-07-01T00:00:00%2B0000"
мне больше интересно, как они проходят с localhost здесь :)

2020-07-09 10:41 UTC, 810411 commented on hw12_13_14_15_calendar/tests/integration/features/list_events.feature
> +    When I send "GET" request to "http://localhost:8888/events/day?datetime=2020-07-01T00:00:00%2B0000"
ну я же через переменную окружения в docker compose говорю им что хост calendar, дальше в файлах _test есть логика по этому поводу

2020-07-09 10:42 UTC, 810411 commented on .golangci.yml
> +    - gofumpt
тогда извиняюсь. думаю с моим мнением все понятно

2020-07-09 10:49 UTC, 810411 commented
> 5 / 10

а вот ваш результат интересный, это называется что надо решать проблемы в моменте и месте их появления. предпосылки были в предыдущем дз по api, тогда не прошли мои юнит тесты по rest api в трависе во время сдачи и я их просто подсократил для экономии времени ))) - но закон сохранения энергии суров - теперь придется исправлять баг. баг явно где-то в логике psql repo при работе с datetime. в общем хотел все сделать по быстрее - получилось как всегда

2020-07-09 13:35 UTC, 810411 commented on hw12_13_14_15_calendar/configs/calendar.json
> +    "dsn": "host=postgres port=5432 user=otus password=otus dbname=calendar sslmode=disable"
оставим это на факультатив тому парню из нового потока который зафоркал этот репозиторий у меня

2020-07-11 06:41 UTC, Antonboom commented on hw12_13_14_15_calendar/configs/calendar.json
> +    "dsn": "host=postgres port=5432 user=otus password=otus dbname=calendar sslmode=disable"
🤦

2020-07-11 06:43 UTC, Antonboom approved these changes
Принято
8 / 10

2020-07-13 10:02 UTC, merged